-- ============================================================
-- Which rooms a professor may use — back again
-- ============================================================
-- V10 dropped this table because nobody had ever entered a row. The need turned out to be real
-- after all: a professor who cannot teach in a particular room. Same shape as before, so an old
-- export restored into a fresh database still matches.
CREATE TABLE IF NOT EXISTS professor_room_restriction (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    professor_id     BIGINT      NOT NULL REFERENCES professor (id) ON DELETE CASCADE,
    room_id          BIGINT      NOT NULL REFERENCES room (id) ON DELETE CASCADE,
    restriction_type VARCHAR(32) NOT NULL
);
