-- ============================================================
-- FSGC timetable generator - initial schema
-- Flyway owns the schema; Hibernate validates against it.
-- ============================================================

CREATE TABLE department (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE building (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(255) NOT NULL UNIQUE,
    address VARCHAR(512)
);

CREATE TABLE student_group (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(255) NOT NULL UNIQUE,
    specialization VARCHAR(255) NOT NULL,
    year           INTEGER      NOT NULL,
    study_program  VARCHAR(32)  NOT NULL,
    student_count  INTEGER      NOT NULL,
    department     VARCHAR(255)
);

CREATE TABLE professor (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(255) NOT NULL UNIQUE,
    email          VARCHAR(255),
    title          VARCHAR(128),
    department     VARCHAR(255),
    has_own_laptop BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE room (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               VARCHAR(255) NOT NULL UNIQUE,
    department         VARCHAR(255),
    floor              VARCHAR(64),
    capacity           INTEGER      NOT NULL,
    typology           VARCHAR(32)  NOT NULL,
    building_id        BIGINT       REFERENCES building (id),
    usage_restrictions VARCHAR(1024)
);

CREATE TABLE room_equipment (
    room_id   BIGINT       NOT NULL REFERENCES room (id) ON DELETE CASCADE,
    equipment VARCHAR(128) NOT NULL
);
CREATE INDEX idx_room_equipment_room ON room_equipment (room_id);

CREATE TABLE room_availability (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id     BIGINT      NOT NULL REFERENCES room (id) ON DELETE CASCADE,
    day_of_week VARCHAR(16) NOT NULL,
    start_time  TIME        NOT NULL,
    end_time    TIME        NOT NULL
);
CREATE INDEX idx_room_availability_room ON room_availability (room_id);

CREATE TABLE subject (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(255) NOT NULL UNIQUE,
    name       VARCHAR(512) NOT NULL,
    department VARCHAR(255)
);

CREATE TABLE time_slot (
    id          BIGINT      PRIMARY KEY,
    day_of_week VARCHAR(16) NOT NULL,
    slot_index  INTEGER     NOT NULL,
    start_time  TIME        NOT NULL,
    end_time    TIME        NOT NULL
);

CREATE TABLE scheduled_activity (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id            BIGINT      NOT NULL REFERENCES subject (id),
    professor_id          BIGINT      REFERENCES professor (id),
    activity_type         VARCHAR(32) NOT NULL,
    duration_in_slots     INTEGER     NOT NULL DEFAULT 1,
    week_parity           VARCHAR(32) NOT NULL DEFAULT 'EVERY_WEEK',
    special_category      VARCHAR(32) NOT NULL DEFAULT 'NORMAL',
    requires_amphitheater BOOLEAN     NOT NULL DEFAULT FALSE,
    raw_type              VARCHAR(128),
    time_slot_id          BIGINT      REFERENCES time_slot (id),
    room_id               BIGINT      REFERENCES room (id)
);

CREATE TABLE activity_student_group (
    activity_id      BIGINT NOT NULL REFERENCES scheduled_activity (id) ON DELETE CASCADE,
    student_group_id BIGINT NOT NULL REFERENCES student_group (id),
    PRIMARY KEY (activity_id, student_group_id)
);

CREATE TABLE blocked_day_rule (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_program VARCHAR(32) NOT NULL,
    year          INTEGER     NOT NULL,
    day_of_week   VARCHAR(16) NOT NULL,
    semester      VARCHAR(64),
    academic_year VARCHAR(64)
);

CREATE TABLE special_block_rule (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_group_id BIGINT      REFERENCES student_group (id),
    specialization   VARCHAR(255),
    year             INTEGER,
    day_of_week      VARCHAR(16) NOT NULL,
    time_slot_id     BIGINT      NOT NULL REFERENCES time_slot (id),
    category         VARCHAR(32) NOT NULL,
    semester         VARCHAR(64),
    academic_year    VARCHAR(64)
);

CREATE TABLE professor_unavailability (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    professor_id BIGINT      NOT NULL REFERENCES professor (id) ON DELETE CASCADE,
    day_of_week  VARCHAR(16) NOT NULL,
    start_time   TIME,
    end_time     TIME
);

CREATE TABLE professor_room_restriction (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    professor_id     BIGINT      NOT NULL REFERENCES professor (id) ON DELETE CASCADE,
    room_id          BIGINT      NOT NULL REFERENCES room (id) ON DELETE CASCADE,
    restriction_type VARCHAR(32) NOT NULL
);

CREATE TABLE constraint_weights (
    id                    BIGINT  PRIMARY KEY,
    daily_load_balance    INTEGER NOT NULL,
    group_gap             INTEGER NOT NULL,
    late_hours_license    INTEGER NOT NULL,
    compactness           INTEGER NOT NULL,
    global_weekly_balance INTEGER NOT NULL,
    professor_preference  INTEGER NOT NULL
);
