-- ============================================================
-- Snapshots of a generated/edited timetable, so a good result can be
-- kept and restored later. Solver jobs live only in memory, and
-- scheduled_activity holds a single current assignment, so without
-- these tables every regeneration overwrote the previous timetable.
--
-- activity_id / time_slot_id / room_id are deliberately NOT foreign
-- keys: a snapshot must survive later edits to the base data. Rows
-- that no longer resolve are skipped (and reported) on restore.
-- ============================================================

CREATE TABLE saved_timetable (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(200)  NOT NULL,
    note             VARCHAR(1000),
    created_at       TIMESTAMP     NOT NULL,
    score            VARCHAR(64),
    total_activities INTEGER       NOT NULL,
    assigned_count   INTEGER       NOT NULL
);

CREATE TABLE saved_timetable_entry (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    saved_timetable_id BIGINT NOT NULL REFERENCES saved_timetable (id) ON DELETE CASCADE,
    activity_id        BIGINT NOT NULL,
    time_slot_id       BIGINT,
    room_id            BIGINT
);

CREATE INDEX idx_saved_entry_parent ON saved_timetable_entry (saved_timetable_id);
