-- ============================================================
-- Rooms are now available on every module by default; the user marks the
-- exceptions. Previously room_availability listed when a room COULD be used,
-- which meant a room with no rows was unusable, and the imported 08:00-20:00
-- windows silently blocked module 8 (19:40-21:10) for every room.
--
-- room_availability is kept (the Excel import still records what the file said)
-- but the solver now reads room_unavailability instead.
-- ============================================================

CREATE TABLE room_unavailability (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id     BIGINT      NOT NULL REFERENCES room (id) ON DELETE CASCADE,
    day_of_week VARCHAR(16) NOT NULL,
    start_time  TIME        NOT NULL,
    end_time    TIME        NOT NULL,
    reason      VARCHAR(200)
);

CREATE INDEX idx_room_unavail_room ON room_unavailability (room_id);
